image:
  - Visual Studio 2019

environment:
  BOOST_ROOT: C:\local\boost_1_69_0
  BOOST_LIBRARYDIR: C:\local\boost_1_69_0\lib64-msvc-14

init:
  - set PATH=c:\Python37;c:\Python37\Scripts;%PATH%

build_script:
  - md build
  - cd build
  - cmake -G "Visual Studio 16 2019" -A x64 .. -DARCH=default -DOPENSSL_ROOT_DIR=C:\OpenSSL-v111-Win64
  - MSBuild Bitcoinnova.sln /p:CLToolPath=c:\Python37\Scripts\ /p:Configuration=Release /m
  - src\Release\cryptotest.exe

after_build:
  - clcache -s
  - if not defined APPVEYOR_REPO_TAG_NAME (set APPVEYOR_REPO_TAG_NAME=%APPVEYOR_REPO_COMMIT%)
  - cd src\Release
  - mkdir bitcoinnova-%APPVEYOR_REPO_TAG_NAME%
  - copy *.exe bitcoinnova-%APPVEYOR_REPO_TAG_NAME%
  - copy ..\..\..\LICENSE bitcoinnova-%APPVEYOR_REPO_TAG_NAME%
  - 7z a bitcoinnova-%APPVEYOR_REPO_TAG_NAME%-windows.zip bitcoinnova-%APPVEYOR_REPO_TAG_NAME%
  - copy bitcoinnova-%APPVEYOR_REPO_TAG_NAME%-windows.zip ..\..\..\

artifacts:
  - path: bitcoinnova-$(APPVEYOR_REPO_TAG_NAME)-windows.zip
    name: BitcoinNovaRelease

deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: r7Vjf/6ZJqMnmvJg+Wa1WPgkTODBCzEbcLkywN3DA0zmIheeqlYVtCyCX1fwkf0z
    repository: BitcoinNova/bitcoinnova
    artifact: BitcoinNovaRelease
    draft: false
    force_update: true
    on:
      branch: master
      appveyor_repo_tag: true
